author_id = "lux"
app_id = "shoot"
author_name = "Lux"
app_name = "Shoot!"

[files]
lvl1 = { path = "levels/1.txt", copy = true }
lvl2 = { path = "levels/2.txt", copy = true }
lvl3 = { path = "levels/3.txt", copy = true }
lvl4 = { path = "levels/4.txt", copy = true }
lvl5 = { path = "levels/5.txt", copy = true }
lvl6 = { path = "levels/6.txt", copy = true }
